WHENEVER SQLERROR EXIT SQL.SQLCODE;

alter session set container = xepdb1;
alter session set current_schema = backend;

create table student (
   s_id       varchar2(10) not null,
   s_pwd      varchar2(30) not null,
   s_name     varchar2(30) not null,
   s_major    varchar2(30) not null,
   s_addr     varchar2(100),
   s_phone    varchar2(20),
   s_email    varchar2(100),
   s_year     number(1) default 1 not null,
   s_status   varchar2(20) default 'ENROLLED' not null,
   created_at timestamp default current_timestamp,
   constraint pk_student primary key ( s_id ),
   constraint chk_student_year check ( s_year between 1 and 6 ),
   constraint chk_student_status
      check ( s_status in ( 'ENROLLED',
                            'LEAVE',
                            'GRADUATED',
                            'WITHDRAWN' ) )
);

create table professor (
   p_id     varchar2(6) not null,
   p_name   varchar2(10) not null,
   p_major  varchar2(30),
   p_office varchar2(30),
   p_phone  varchar2(20),
   p_pwd    varchar2(30) not null,
   p_email  varchar2(100),
   constraint pk_professor primary key ( p_id ),
   constraint chk_professor_id check ( regexp_like ( p_id,
                                                     '^P[0-9]{5}$' ) )
);

create table user_account (
   user_id       number(19) generated by default as identity not null,
   login_id      varchar2(50) not null,
   password_hash varchar2(255) not null,
   role          varchar2(20) not null,
   email         varchar2(100),
   phone         varchar2(20),
   is_active     number(1) default 1,
   last_login_at timestamp,
   created_at    timestamp default current_timestamp,
   constraint pk_user_account primary key ( user_id ),
   constraint uk_user_account_login_id unique ( login_id ),
   constraint chk_user_account_role check ( role in ( 'STUDENT',
                                                      'PROFESSOR' ) ),
   constraint chk_user_account_active check ( is_active in ( 0,
                                                             1 ) )
);

comment on table user_account is '?듯빀 ?ъ슜??怨꾩젙';
comment on column user_account.login_id is '?숇쾲/?щ쾲';

create index idx_user_account_role on
   user_account (
      role
   );

create table lecture (
   id               number(2) not null,
   no               varchar2(10) not null,
   subject          varchar2(20) not null,
   prof             varchar2(10) not null,
   credit           number(2) default 3 not null,
   p_id             varchar2(6),
   course_type      varchar2(20) not null,
   course_major     varchar2(30) not null,
   target_year      number(1) not null,
   is_english       number(1) default 0 not null,
   textbook         varchar2(200),
   assignment_count number default 0 not null,
   midterm_rate     number default 30 not null,
   final_rate       number default 30 not null,
   assignment_rate  number default 30 not null,
   attendance_rate  number default 10 not null,
   prerequisite     varchar2(100),
   note             varchar2(500),
   constraint pk_lecture primary key ( id ),
   constraint uk_lecture_no unique ( no ),
   constraint fk_lecture_professor foreign key ( p_id )
      references professor ( p_id ),
   constraint chk_lecture_credit check ( credit between 1 and 6 ),
   constraint chk_lecture_course_type
      check ( course_type in ( '?꾧났?꾩닔',
                               '?꾧났?좏깮',
                               '援먯뼇?꾩닔',
                               '援먯뼇?좏깮' ) ),
   constraint chk_lecture_target_year check ( target_year between 1 and 6 ),
   constraint chk_lecture_is_english check ( is_english in ( 0,
                                                             1 ) ),
   constraint chk_lecture_grading_rate
      check ( midterm_rate >= 0
         and final_rate >= 0
         and assignment_rate >= 0
         and attendance_rate >= 0
         and midterm_rate + final_rate + assignment_rate + attendance_rate = 100 )
);

create table class (
   p_id     varchar2(6),
   c_id     varchar2(10),
   c_no     number,
   c_where  varchar2(30),
   c_year   number(4) not null,
   c_semester number(1) not null,
   c_max    number default 30 not null,
   c_now    number default 0 not null,
   c_status varchar2(10) default 'OPEN' not null,
   constraint pk_class primary key ( c_id,
                                     c_no ),
   constraint fk_class_professor foreign key ( p_id )
      references professor ( p_id ),
   constraint fk_class_lecture foreign key ( c_id )
      references lecture ( no ),
   constraint chk_class_capacity
      check ( c_max >= 0
         and c_now >= 0
         and c_now <= c_max ),
   constraint chk_class_semester check ( c_semester in ( 1, 2 ) ),
   constraint chk_class_status
      check ( c_status in ( 'OPEN',
                            'CLOSED',
                            'CANCELLED' ) )
);

create table class_time (
   time_id number generated by default as identity not null,
   p_id    varchar2(6),
   c_id    varchar2(10) not null,
   c_no    number not null,
   c_day   varchar2(3) not null,
   c_start varchar2(5) not null,
   c_end   varchar2(5) not null,
   constraint pk_class_time primary key ( time_id ),
   constraint fk_class_time_class
      foreign key ( c_id,
                    c_no )
         references class ( c_id,
                            c_no )
            on delete cascade,
   constraint fk_class_time_professor foreign key ( p_id )
      references professor ( p_id ),
   constraint chk_class_time_day
      check ( c_day in ( 'MON',
                         'TUE',
                         'WED',
                         'THU',
                         'FRI',
                         'SAT' ) ),
   constraint chk_class_time_start check ( regexp_like ( c_start,
                                                         '^([01][0-9]|2[0-3]):[0-5][0-9]$' ) ),
   constraint chk_class_time_end check ( regexp_like ( c_end,
                                                       '^([01][0-9]|2[0-3]):[0-5][0-9]$' ) ),
   constraint chk_class_time_range check ( c_start < c_end )
);

create table enroll (
   e_id           number generated by default as identity not null,
   s_id           varchar2(10) not null,
   c_id           varchar2(10) not null,
   c_no           number not null,
   e_year         number not null,
   e_semester     number not null,
   e_date         timestamp default current_timestamp not null,
   e_status       varchar2(10) default 'ENROLLED' not null,
   e_drop_date    timestamp,
   professor_note clob,
   constraint pk_enroll primary key ( e_id ),
   constraint fk_enroll_student foreign key ( s_id )
      references student ( s_id ),
   constraint fk_enroll_class
      foreign key ( c_id,
                    c_no )
         references class ( c_id,
                            c_no ),
   constraint uk_enroll_active unique ( s_id,
                                        c_id,
                                        e_year,
                                        e_semester ),
   constraint chk_enroll_semester check ( e_semester in ( 1,
                                                          2 ) ),
   constraint chk_enroll_status
      check ( e_status in ( 'ENROLLED',
                            'DROPPED',
                            'COMPLETED' ) )
);

create index idx_enroll_student_status on
   enroll (
      s_id,
      e_status,
      e_year,
      e_semester
   );
create index idx_class_time_lookup on
   class_time (
      c_id,
      c_no,
      c_day,
      c_start,
      c_end
   );

create table registration_period (
   period_id   number generated by default as identity not null,
   e_year      number not null,
   e_semester  number not null,
   period_type varchar2(10) default 'MAIN' not null,
   start_at    timestamp not null,
   end_at      timestamp not null,
   constraint pk_registration_period primary key ( period_id ),
   constraint chk_registration_period_semester check ( e_semester in ( 1,
                                                                       2 ) ),
   constraint chk_registration_period_type
      check ( period_type in ( 'MAIN',
                               'ADD_DROP',
                               'CANCEL' ) ),
   constraint chk_registration_period_range check ( start_at < end_at )
);

create table cart_item (
   cart_id  number generated by default as identity not null,
   s_id     varchar2(10) not null,
   c_id     varchar2(10) not null,
   c_no     number not null,
   added_at timestamp default current_timestamp,
   constraint pk_cart_item primary key ( cart_id ),
   constraint fk_cart_item_student foreign key ( s_id )
      references student ( s_id )
         on delete cascade,
   constraint fk_cart_item_class
      foreign key ( c_id,
                    c_no )
         references class ( c_id,
                            c_no )
            on delete cascade,
   constraint uk_cart_item unique ( s_id,
                                    c_id,
                                    c_no )
);

create table course_request (
   request_id        number generated by default as identity not null,
   s_id              varchar2(10) not null,
   c_id              varchar2(10) not null,
   c_no              number not null,
   reason            clob not null,
   status            varchar2(20) default 'PENDING' not null,
   requested_at      timestamp default current_timestamp,
   processed_at      timestamp,
   processed_by_p_id varchar2(6),
   constraint pk_course_request primary key ( request_id ),
   constraint fk_course_request_student foreign key ( s_id )
      references student ( s_id )
         on delete cascade,
   constraint fk_course_request_class
      foreign key ( c_id,
                    c_no )
         references class ( c_id,
                            c_no )
            on delete cascade,
   constraint fk_course_request_professor foreign key ( processed_by_p_id )
      references professor ( p_id ),
   constraint uk_course_request unique ( s_id,
                                         c_id,
                                         c_no ),
   constraint chk_course_request_status
      check ( status in ( 'PENDING',
                          'APPROVED',
                          'REJECTED' ) )
);

create table review (
   review_id        number generated by default as identity not null,
   e_id             number not null,
   rating_overall   number(3) not null,
   rating_content   number(3),
   rating_workload  number(3),
   rating_professor number(3),
   difficulty       varchar2(10),
   pros             clob,
   cons             clob,
   advice           clob,
   is_anonymous     number(1) default 1,
   created_at       timestamp default current_timestamp,
   constraint pk_review primary key ( review_id ),
   constraint uk_review_enroll unique ( e_id ),
   constraint fk_review_enroll foreign key ( e_id )
      references enroll ( e_id )
         on delete cascade,
   constraint chk_review_rating_overall check ( rating_overall between 1 and 5 ),
   constraint chk_review_rating_content check ( rating_content between 1 and 5 ),
   constraint chk_review_rating_workload check ( rating_workload between 1 and 5 ),
   constraint chk_review_rating_professor check ( rating_professor between 1 and 5 ),
   constraint chk_review_difficulty
      check ( difficulty in ( 'EASY',
                              'MEDIUM',
                              'HARD' ) ),
   constraint chk_review_anonymous check ( is_anonymous in ( 0,
                                                             1 ) )
);

create table notification (
   notification_id   number generated by default as identity not null,
   recipient_s_id    varchar2(10),
   recipient_p_id    varchar2(6),
   sender_s_id       varchar2(10),
   sender_p_id       varchar2(6),
   target_c_id       varchar2(10),
   target_c_no       number,
   target_request_id number,
   title             varchar2(200) not null,
   body              clob,
   type              varchar2(30) not null,
   is_read           number(1) default 0,
   created_at        timestamp default current_timestamp,
   constraint pk_notification primary key ( notification_id ),
   constraint fk_notification_recipient_student foreign key ( recipient_s_id )
      references student ( s_id )
         on delete cascade,
   constraint fk_notification_recipient_professor foreign key ( recipient_p_id )
      references professor ( p_id )
         on delete cascade,
   constraint fk_notification_sender_student foreign key ( sender_s_id )
      references student ( s_id )
         on delete set null,
   constraint fk_notification_sender_professor foreign key ( sender_p_id )
      references professor ( p_id )
         on delete set null,
   constraint fk_notification_class
      foreign key ( target_c_id,
                    target_c_no )
         references class ( c_id,
                            c_no )
            on delete set null,
   constraint fk_notification_request foreign key ( target_request_id )
      references course_request ( request_id )
         on delete set null,
   constraint chk_notification_recipient
      check ( ( recipient_s_id is not null
         and recipient_p_id is null )
          or ( recipient_s_id is null
         and recipient_p_id is not null ) ),
   constraint chk_notification_type
      check ( type in ( 'COURSE_REQUEST',
                        'COURSE_REQUEST_RESULT',
                        'COURSE_REVIEW',
                        'PROFESSOR_MESSAGE',
                        'SYSTEM' ) ),
   constraint chk_notification_read check ( is_read in ( 0,
                                                         1 ) )
);

create index idx_notification_student_unread on
   notification (
      recipient_s_id,
      is_read,
      created_at
   desc );
create index idx_notification_professor_unread on
   notification (
      recipient_p_id,
      is_read,
      created_at
   desc );

create table refresh_token (
   token_id    number generated by default as identity not null,
   login_id    varchar2(50) not null,
   login_type  varchar2(10) not null,
   token_hash  varchar2(255) not null,
   remember_me number(1) default 0 not null,
   expires_at  timestamp not null,
   revoked_at  timestamp,
   created_at  timestamp default current_timestamp,
   constraint pk_refresh_token primary key ( token_id ),
   constraint uk_refresh_token_hash unique ( token_hash ),
   constraint fk_refresh_token_user_account foreign key ( login_id )
      references user_account ( login_id )
         on delete cascade,
   constraint chk_refresh_login_type check ( login_type in ( 'STUDENT',
                                                             'PROFESSOR' ) ),
   constraint chk_refresh_remember check ( remember_me in ( 0,
                                                            1 ) )
);

create index idx_refresh_token_login_active on
   refresh_token (
      login_id,
      login_type,
      revoked_at,
      expires_at
   );

