WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = backend;

BEGIN
  FOR object_name IN (
    SELECT 'TRG_ENROLL_CLASS_COUNT' name, 'TRIGGER' type FROM dual UNION ALL
    SELECT 'INSERTENROLL', 'PROCEDURE' FROM dual UNION ALL
    SELECT 'DELETEENROLL', 'PROCEDURE' FROM dual UNION ALL
    SELECT 'OPENAVAILABLECLASSCURSOR', 'PROCEDURE' FROM dual UNION ALL
    SELECT 'DATE2ENROLLSEMESTER', 'FUNCTION' FROM dual UNION ALL
    SELECT 'DATE2ENROLLYEAR', 'FUNCTION' FROM dual
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP ' || object_name.type || ' ' || object_name.name;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE NOT IN (-4043, -4080) THEN
          RAISE;
        END IF;
    END;
  END LOOP;
END;
/

BEGIN
  FOR table_name IN (
    SELECT 'NOTIFICATION' name FROM dual UNION ALL
    SELECT 'REFRESH_TOKEN' FROM dual UNION ALL
    SELECT 'REVIEW' FROM dual UNION ALL
    SELECT 'COURSE_REQUEST' FROM dual UNION ALL
    SELECT 'CART_ITEM' FROM dual UNION ALL
    SELECT 'REGISTRATION_PERIOD' FROM dual UNION ALL
    SELECT 'ENROLL' FROM dual UNION ALL
    SELECT 'CLASS_TIME' FROM dual UNION ALL
    SELECT 'CLASS' FROM dual UNION ALL
    SELECT 'LECTURE' FROM dual UNION ALL
    SELECT 'PROFESSOR' FROM dual UNION ALL
    SELECT 'STUDENT' FROM dual
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || table_name.name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
  END LOOP;
END;
/

CREATE TABLE student (
  s_id VARCHAR2(10) NOT NULL,
  s_pwd VARCHAR2(30) NOT NULL,
  s_name VARCHAR2(30) NOT NULL,
  s_major VARCHAR2(30) NOT NULL,
  s_addr VARCHAR2(100),
  s_phone VARCHAR2(20),
  s_email VARCHAR2(100),
  s_year NUMBER(1) DEFAULT 1 NOT NULL,
  s_status VARCHAR2(20) DEFAULT 'ENROLLED' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_student PRIMARY KEY (s_id),
  CONSTRAINT chk_student_year CHECK (s_year BETWEEN 1 AND 6),
  CONSTRAINT chk_student_status CHECK (s_status IN ('ENROLLED', 'LEAVE', 'GRADUATED', 'WITHDRAWN'))
);

CREATE TABLE professor (
  p_id VARCHAR2(6) NOT NULL,
  p_name VARCHAR2(10) NOT NULL,
  p_major VARCHAR2(30),
  p_office VARCHAR2(30),
  p_phone VARCHAR2(20),
  p_email VARCHAR2(100),
  CONSTRAINT pk_professor PRIMARY KEY (p_id)
);

CREATE TABLE lecture (
  id NUMBER(2) NOT NULL,
  no NUMBER(4) NOT NULL,
  subject VARCHAR2(20) NOT NULL,
  prof VARCHAR2(10) NOT NULL,
  credit NUMBER(2) DEFAULT 3 NOT NULL,
  p_id VARCHAR2(6),
  CONSTRAINT pk_lecture PRIMARY KEY (id),
  CONSTRAINT uk_lecture_no UNIQUE (no),
  CONSTRAINT fk_lecture_professor FOREIGN KEY (p_id) REFERENCES professor (p_id),
  CONSTRAINT chk_lecture_credit CHECK (credit BETWEEN 1 AND 6)
);

CREATE TABLE class (
  p_id VARCHAR2(6),
  c_id NUMBER,
  c_no NUMBER,
  c_where VARCHAR2(30),
  c_max NUMBER DEFAULT 30 NOT NULL,
  c_now NUMBER DEFAULT 0 NOT NULL,
  c_status VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
  CONSTRAINT pk_class PRIMARY KEY (c_id, c_no),
  CONSTRAINT fk_class_professor FOREIGN KEY (p_id) REFERENCES professor (p_id),
  CONSTRAINT fk_class_lecture FOREIGN KEY (c_id) REFERENCES lecture (no),
  CONSTRAINT chk_class_capacity CHECK (c_max >= 0 AND c_now >= 0 AND c_now <= c_max),
  CONSTRAINT chk_class_status CHECK (c_status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE class_time (
  time_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  p_id VARCHAR2(6),
  c_id NUMBER NOT NULL,
  c_no NUMBER NOT NULL,
  c_day VARCHAR2(3) NOT NULL,
  c_start VARCHAR2(5) NOT NULL,
  c_end VARCHAR2(5) NOT NULL,
  CONSTRAINT pk_class_time PRIMARY KEY (time_id),
  CONSTRAINT fk_class_time_class FOREIGN KEY (c_id, c_no) REFERENCES class (c_id, c_no) ON DELETE CASCADE,
  CONSTRAINT fk_class_time_professor FOREIGN KEY (p_id) REFERENCES professor (p_id),
  CONSTRAINT chk_class_time_day CHECK (c_day IN ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT')),
  CONSTRAINT chk_class_time_start CHECK (REGEXP_LIKE(c_start, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT chk_class_time_end CHECK (REGEXP_LIKE(c_end, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT chk_class_time_range CHECK (c_start < c_end)
);

CREATE TABLE enroll (
  e_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  s_id VARCHAR2(10) NOT NULL,
  c_id NUMBER NOT NULL,
  c_no NUMBER NOT NULL,
  e_year NUMBER NOT NULL,
  e_semester NUMBER NOT NULL,
  e_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  e_status VARCHAR2(10) DEFAULT 'ENROLLED' NOT NULL,
  e_drop_date TIMESTAMP,
  professor_note CLOB,
  CONSTRAINT pk_enroll PRIMARY KEY (e_id),
  CONSTRAINT fk_enroll_student FOREIGN KEY (s_id) REFERENCES student (s_id),
  CONSTRAINT fk_enroll_class FOREIGN KEY (c_id, c_no) REFERENCES class (c_id, c_no),
  CONSTRAINT uk_enroll_active UNIQUE (s_id, c_id, e_year, e_semester),
  CONSTRAINT chk_enroll_semester CHECK (e_semester IN (1, 2)),
  CONSTRAINT chk_enroll_status CHECK (e_status IN ('ENROLLED', 'DROPPED', 'COMPLETED'))
);

CREATE INDEX idx_enroll_student_status ON enroll (s_id, e_status, e_year, e_semester);
CREATE INDEX idx_class_time_lookup ON class_time (c_id, c_no, c_day, c_start, c_end);

CREATE TABLE registration_period (
  period_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  e_year NUMBER NOT NULL,
  e_semester NUMBER NOT NULL,
  period_type VARCHAR2(10) DEFAULT 'MAIN' NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  CONSTRAINT pk_registration_period PRIMARY KEY (period_id),
  CONSTRAINT chk_registration_period_semester CHECK (e_semester IN (1, 2)),
  CONSTRAINT chk_registration_period_type CHECK (period_type IN ('MAIN', 'ADD_DROP', 'CANCEL')),
  CONSTRAINT chk_registration_period_range CHECK (start_at < end_at)
);

CREATE TABLE cart_item (
  cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  s_id VARCHAR2(10) NOT NULL,
  c_id NUMBER NOT NULL,
  c_no NUMBER NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cart_item PRIMARY KEY (cart_id),
  CONSTRAINT fk_cart_item_student FOREIGN KEY (s_id) REFERENCES student (s_id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_class FOREIGN KEY (c_id, c_no) REFERENCES class (c_id, c_no) ON DELETE CASCADE,
  CONSTRAINT uk_cart_item UNIQUE (s_id, c_id, c_no)
);

CREATE TABLE course_request (
  request_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  s_id VARCHAR2(10) NOT NULL,
  c_id NUMBER NOT NULL,
  c_no NUMBER NOT NULL,
  reason CLOB NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP,
  processed_by_p_id VARCHAR2(6),
  CONSTRAINT pk_course_request PRIMARY KEY (request_id),
  CONSTRAINT fk_course_request_student FOREIGN KEY (s_id) REFERENCES student (s_id) ON DELETE CASCADE,
  CONSTRAINT fk_course_request_class FOREIGN KEY (c_id, c_no) REFERENCES class (c_id, c_no) ON DELETE CASCADE,
  CONSTRAINT fk_course_request_professor FOREIGN KEY (processed_by_p_id) REFERENCES professor (p_id),
  CONSTRAINT uk_course_request UNIQUE (s_id, c_id, c_no),
  CONSTRAINT chk_course_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE review (
  review_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  e_id NUMBER NOT NULL,
  rating_overall NUMBER(3) NOT NULL,
  rating_content NUMBER(3),
  rating_workload NUMBER(3),
  rating_professor NUMBER(3),
  difficulty VARCHAR2(10),
  pros CLOB,
  cons CLOB,
  advice CLOB,
  is_anonymous NUMBER(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_review PRIMARY KEY (review_id),
  CONSTRAINT uk_review_enroll UNIQUE (e_id),
  CONSTRAINT fk_review_enroll FOREIGN KEY (e_id) REFERENCES enroll (e_id) ON DELETE CASCADE,
  CONSTRAINT chk_review_rating_overall CHECK (rating_overall BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_content CHECK (rating_content BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_workload CHECK (rating_workload BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_professor CHECK (rating_professor BETWEEN 1 AND 5),
  CONSTRAINT chk_review_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
  CONSTRAINT chk_review_anonymous CHECK (is_anonymous IN (0, 1))
);

CREATE TABLE notification (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient_s_id VARCHAR2(10),
  recipient_p_id VARCHAR2(6),
  sender_s_id VARCHAR2(10),
  sender_p_id VARCHAR2(6),
  target_c_id NUMBER,
  target_c_no NUMBER,
  target_request_id NUMBER,
  title VARCHAR2(200) NOT NULL,
  body CLOB,
  type VARCHAR2(30) NOT NULL,
  is_read NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notification PRIMARY KEY (notification_id),
  CONSTRAINT fk_notification_recipient_student FOREIGN KEY (recipient_s_id) REFERENCES student (s_id) ON DELETE CASCADE,
  CONSTRAINT fk_notification_recipient_professor FOREIGN KEY (recipient_p_id) REFERENCES professor (p_id) ON DELETE CASCADE,
  CONSTRAINT fk_notification_sender_student FOREIGN KEY (sender_s_id) REFERENCES student (s_id) ON DELETE SET NULL,
  CONSTRAINT fk_notification_sender_professor FOREIGN KEY (sender_p_id) REFERENCES professor (p_id) ON DELETE SET NULL,
  CONSTRAINT fk_notification_class FOREIGN KEY (target_c_id, target_c_no) REFERENCES class (c_id, c_no) ON DELETE SET NULL,
  CONSTRAINT fk_notification_request FOREIGN KEY (target_request_id) REFERENCES course_request (request_id) ON DELETE SET NULL,
  CONSTRAINT chk_notification_recipient CHECK (
    (recipient_s_id IS NOT NULL AND recipient_p_id IS NULL)
    OR (recipient_s_id IS NULL AND recipient_p_id IS NOT NULL)
  ),
  CONSTRAINT chk_notification_type CHECK (
    type IN ('COURSE_REQUEST', 'COURSE_REQUEST_RESULT', 'COURSE_REVIEW', 'PROFESSOR_MESSAGE', 'SYSTEM')
  ),
  CONSTRAINT chk_notification_read CHECK (is_read IN (0, 1))
);

CREATE INDEX idx_notification_student_unread ON notification (recipient_s_id, is_read, created_at DESC);
CREATE INDEX idx_notification_professor_unread ON notification (recipient_p_id, is_read, created_at DESC);

CREATE TABLE refresh_token (
  token_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  login_id VARCHAR2(50) NOT NULL,
  login_type VARCHAR2(10) NOT NULL,
  token_hash VARCHAR2(255) NOT NULL,
  remember_me NUMBER(1) DEFAULT 0 NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_refresh_token PRIMARY KEY (token_id),
  CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_refresh_login_type CHECK (login_type IN ('STUDENT', 'PROFESSOR')),
  CONSTRAINT chk_refresh_remember CHECK (remember_me IN (0, 1))
);

CREATE INDEX idx_refresh_token_login_active ON refresh_token (login_id, login_type, revoked_at, expires_at);

CREATE OR REPLACE FUNCTION Date2EnrollYear(p_date IN DATE)
RETURN NUMBER
IS
  v_month NUMBER;
BEGIN
  v_month := TO_NUMBER(TO_CHAR(p_date, 'MM'));

  IF v_month IN (11, 12) THEN
    RETURN TO_NUMBER(TO_CHAR(ADD_MONTHS(p_date, 2), 'YYYY'));
  END IF;

  RETURN TO_NUMBER(TO_CHAR(p_date, 'YYYY'));
END;
/

CREATE OR REPLACE FUNCTION Date2EnrollSemester(p_date IN DATE)
RETURN NUMBER
IS
  v_month NUMBER;
BEGIN
  v_month := TO_NUMBER(TO_CHAR(p_date, 'MM'));

  IF v_month BETWEEN 1 AND 4 THEN
    RETURN 1;
  ELSIF v_month BETWEEN 5 AND 10 THEN
    RETURN 2;
  ELSE
    RETURN 1;
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE OpenAvailableClassCursor(
  p_s_id IN student.s_id%TYPE,
  p_result OUT SYS_REFCURSOR
)
IS
  v_year NUMBER;
  v_semester NUMBER;
BEGIN
  v_year := Date2EnrollYear(SYSDATE);
  v_semester := Date2EnrollSemester(SYSDATE);

  OPEN p_result FOR
    SELECT
      l.no AS c_id,
      c.c_no,
      l.subject,
      l.prof,
      l.credit,
      c.c_where,
      c.c_max,
      c.c_now
    FROM lecture l
    JOIN class c ON c.c_id = l.no
    WHERE c.c_status = 'OPEN'
      AND NOT EXISTS (
        SELECT 1
        FROM enroll e
        WHERE e.s_id = p_s_id
          AND e.c_id = c.c_id
          AND e.e_year = v_year
          AND e.e_semester = v_semester
          AND e.e_status = 'ENROLLED'
      )
    ORDER BY l.no, c.c_no;
END;
/

CREATE OR REPLACE PROCEDURE InsertEnroll(
  p_s_id IN student.s_id%TYPE,
  p_c_id IN class.c_id%TYPE,
  p_c_no IN class.c_no%TYPE,
  p_result OUT VARCHAR2
)
IS
  v_year NUMBER;
  v_semester NUMBER;
  v_credit NUMBER;
  v_total_credit NUMBER;
  v_duplicate_count NUMBER;
  v_capacity_count NUMBER;
  v_conflict_count NUMBER := 0;

  CURSOR enrolled_time_cur(
    cur_s_id student.s_id%TYPE,
    cur_year NUMBER,
    cur_semester NUMBER
  ) IS
    SELECT ct.c_day, ct.c_start, ct.c_end
    FROM enroll e
    JOIN class_time ct ON ct.c_id = e.c_id AND ct.c_no = e.c_no
    WHERE e.s_id = cur_s_id
      AND e.e_year = cur_year
      AND e.e_semester = cur_semester
      AND e.e_status = 'ENROLLED';
BEGIN
  v_year := Date2EnrollYear(SYSDATE);
  v_semester := Date2EnrollSemester(SYSDATE);

  SELECT l.credit
  INTO v_credit
  FROM lecture l
  JOIN class c ON c.c_id = l.no
  WHERE c.c_id = p_c_id
    AND c.c_no = p_c_no
    AND c.c_status = 'OPEN'
  FOR UPDATE;

  SELECT COALESCE(SUM(l.credit), 0)
  INTO v_total_credit
  FROM enroll e
  JOIN lecture l ON l.no = e.c_id
  WHERE e.s_id = p_s_id
    AND e.e_year = v_year
    AND e.e_semester = v_semester
    AND e.e_status = 'ENROLLED';

  IF v_total_credit + v_credit > 18 THEN
    p_result := 'MAX_CREDIT_EXCEEDED';
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO v_duplicate_count
  FROM enroll e
  WHERE e.s_id = p_s_id
    AND e.c_id = p_c_id
    AND e.e_year = v_year
    AND e.e_semester = v_semester
    AND e.e_status = 'ENROLLED';

  IF v_duplicate_count > 0 THEN
    p_result := 'DUPLICATE_COURSE';
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO v_capacity_count
  FROM class c
  WHERE c.c_id = p_c_id
    AND c.c_no = p_c_no
    AND c.c_now >= c.c_max;

  IF v_capacity_count > 0 THEN
    p_result := 'CAPACITY_FULL';
    RETURN;
  END IF;

  FOR current_time IN enrolled_time_cur(p_s_id, v_year, v_semester) LOOP
    SELECT COUNT(*)
    INTO v_conflict_count
    FROM class_time new_time
    WHERE new_time.c_id = p_c_id
      AND new_time.c_no = p_c_no
      AND new_time.c_day = current_time.c_day
      AND new_time.c_start < current_time.c_end
      AND new_time.c_end > current_time.c_start;

    IF v_conflict_count > 0 THEN
      p_result := 'TIME_CONFLICT';
      RETURN;
    END IF;
  END LOOP;

  INSERT INTO enroll (s_id, c_id, c_no, e_year, e_semester, e_date, e_status)
  VALUES (p_s_id, p_c_id, p_c_no, v_year, v_semester, SYSTIMESTAMP, 'ENROLLED');

  p_result := 'ENROLL_SUCCESS';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_result := 'CLASS_NOT_FOUND';
  WHEN DUP_VAL_ON_INDEX THEN
    p_result := 'DUPLICATE_COURSE';
  WHEN OTHERS THEN
    p_result := 'SQLCODE=' || SQLCODE;
END;
/

CREATE OR REPLACE PROCEDURE DeleteEnroll(
  p_s_id IN student.s_id%TYPE,
  p_c_id IN class.c_id%TYPE,
  p_c_no IN class.c_no%TYPE,
  p_result OUT VARCHAR2
)
IS
  v_year NUMBER;
  v_semester NUMBER;
  v_count NUMBER;
BEGIN
  v_year := Date2EnrollYear(SYSDATE);
  v_semester := Date2EnrollSemester(SYSDATE);

  UPDATE enroll
  SET e_status = 'DROPPED',
      e_drop_date = SYSTIMESTAMP
  WHERE s_id = p_s_id
    AND c_id = p_c_id
    AND c_no = p_c_no
    AND e_year = v_year
    AND e_semester = v_semester
    AND e_status = 'ENROLLED';

  v_count := SQL%ROWCOUNT;

  IF v_count = 0 THEN
    p_result := 'ENROLL_NOT_FOUND';
  ELSE
    p_result := 'DELETE_SUCCESS';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    p_result := 'SQLCODE=' || SQLCODE;
END;
/

CREATE OR REPLACE TRIGGER trg_enroll_class_count
AFTER INSERT OR UPDATE OR DELETE ON enroll
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF :NEW.e_status = 'ENROLLED' THEN
      UPDATE class
      SET c_now = c_now + 1
      WHERE c_id = :NEW.c_id
        AND c_no = :NEW.c_no;
    END IF;
  ELSIF DELETING THEN
    IF :OLD.e_status = 'ENROLLED' THEN
      UPDATE class
      SET c_now = GREATEST(0, c_now - 1)
      WHERE c_id = :OLD.c_id
        AND c_no = :OLD.c_no;
    END IF;
  ELSIF UPDATING THEN
    IF :OLD.e_status = 'ENROLLED' AND :NEW.e_status != 'ENROLLED' THEN
      UPDATE class
      SET c_now = GREATEST(0, c_now - 1)
      WHERE c_id = :OLD.c_id
        AND c_no = :OLD.c_no;
    ELSIF :OLD.e_status != 'ENROLLED' AND :NEW.e_status = 'ENROLLED' THEN
      UPDATE class
      SET c_now = c_now + 1
      WHERE c_id = :NEW.c_id
        AND c_no = :NEW.c_no;
    END IF;
  END IF;
END;
/
