-- Oracle schema target follows .env.example: DB_USERNAME=backend.
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = backend;

BEGIN
  FOR table_name IN (
    SELECT 'ANNOUNCEMENT' name FROM dual UNION ALL
    SELECT 'NOTIFICATION' FROM dual UNION ALL
    SELECT 'REVIEW' FROM dual UNION ALL
    SELECT 'GRADE' FROM dual UNION ALL
    SELECT 'ENROLLMENT' FROM dual UNION ALL
    SELECT 'WAITLIST' FROM dual UNION ALL
    SELECT 'CART_ITEM' FROM dual UNION ALL
    SELECT 'REGISTRATION_PERIOD' FROM dual UNION ALL
    SELECT 'SECTION_SCHEDULE' FROM dual UNION ALL
    SELECT 'COURSE_SECTION' FROM dual UNION ALL
    SELECT 'CLASSROOM' FROM dual UNION ALL
    SELECT 'SEMESTER' FROM dual UNION ALL
    SELECT 'PREREQUISITE' FROM dual UNION ALL
    SELECT 'COURSE' FROM dual UNION ALL
    SELECT 'ADMIN' FROM dual UNION ALL
    SELECT 'PROFESSOR' FROM dual UNION ALL
    SELECT 'STUDENT' FROM dual UNION ALL
    SELECT 'USER_ACCOUNT' FROM dual UNION ALL
    SELECT 'DEPARTMENT' FROM dual
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || table_name.name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
  END LOOP;
END;
/

CREATE TABLE department (
  dept_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dept_code VARCHAR2(20) NOT NULL,
  dept_name VARCHAR2(100) NOT NULL,
  college VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_department PRIMARY KEY (dept_id),
  CONSTRAINT uk_department_dept_code UNIQUE (dept_code)
);

COMMENT ON TABLE department IS '학과 정보';
COMMENT ON COLUMN department.college IS '단과대학';

CREATE TABLE user_account (
  user_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  login_id VARCHAR2(50) NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) NOT NULL,
  email VARCHAR2(100),
  phone VARCHAR2(20),
  is_active NUMBER(1) DEFAULT 1,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user_account PRIMARY KEY (user_id),
  CONSTRAINT uk_user_account_login_id UNIQUE (login_id),
  CONSTRAINT chk_user_account_role CHECK (role IN ('STUDENT', 'PROFESSOR', 'ADMIN')),
  CONSTRAINT chk_user_account_active CHECK (is_active IN (0, 1))
);

COMMENT ON TABLE user_account IS '통합 사용자 계정';
COMMENT ON COLUMN user_account.login_id IS '학번/사번';

CREATE INDEX idx_user_account_role ON user_account (role);

CREATE TABLE student (
  student_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id NUMBER(19) NOT NULL,
  dept_id NUMBER(19) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  year_level NUMBER(3) NOT NULL,
  enrollment_status VARCHAR2(20) DEFAULT 'ENROLLED',
  cum_gpa NUMBER(3,2) DEFAULT 0.00,
  total_credits NUMBER(10) DEFAULT 0,
  admission_year NUMBER(10) NOT NULL,
  CONSTRAINT pk_student PRIMARY KEY (student_id),
  CONSTRAINT uk_student_user_id UNIQUE (user_id),
  CONSTRAINT fk_student_user_account FOREIGN KEY (user_id) REFERENCES user_account (user_id) ON DELETE CASCADE,
  CONSTRAINT fk_student_department FOREIGN KEY (dept_id) REFERENCES department (dept_id),
  CONSTRAINT chk_student_year_level CHECK (year_level BETWEEN 1 AND 6),
  CONSTRAINT chk_student_status CHECK (enrollment_status IN ('ENROLLED', 'LEAVE', 'GRADUATED', 'WITHDRAWN'))
);

COMMENT ON TABLE student IS '학생';

CREATE INDEX idx_student_dept_year ON student (dept_id, year_level);

CREATE TABLE professor (
  professor_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id NUMBER(19) NOT NULL,
  dept_id NUMBER(19) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  title VARCHAR2(30),
  office VARCHAR2(50),
  CONSTRAINT pk_professor PRIMARY KEY (professor_id),
  CONSTRAINT uk_professor_user_id UNIQUE (user_id),
  CONSTRAINT fk_professor_user_account FOREIGN KEY (user_id) REFERENCES user_account (user_id) ON DELETE CASCADE,
  CONSTRAINT fk_professor_department FOREIGN KEY (dept_id) REFERENCES department (dept_id)
);

COMMENT ON TABLE professor IS '교수';
COMMENT ON COLUMN professor.title IS '교수/부교수/조교수/강사';

CREATE TABLE admin (
  admin_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id NUMBER(19) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  department VARCHAR2(50),
  CONSTRAINT pk_admin PRIMARY KEY (admin_id),
  CONSTRAINT uk_admin_user_id UNIQUE (user_id),
  CONSTRAINT fk_admin_user_account FOREIGN KEY (user_id) REFERENCES user_account (user_id) ON DELETE CASCADE
);

COMMENT ON TABLE admin IS '관리자';
COMMENT ON COLUMN admin.department IS '소속 부서 (학사팀 등)';

CREATE TABLE course (
  course_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_code VARCHAR2(20) NOT NULL,
  course_name VARCHAR2(200) NOT NULL,
  credits NUMBER(3) NOT NULL,
  course_type VARCHAR2(30) NOT NULL,
  dept_id NUMBER(19) NOT NULL,
  target_year NUMBER(3),
  description CLOB,
  is_english NUMBER(1) DEFAULT 0,
  CONSTRAINT pk_course PRIMARY KEY (course_id),
  CONSTRAINT uk_course_course_code UNIQUE (course_code),
  CONSTRAINT fk_course_department FOREIGN KEY (dept_id) REFERENCES department (dept_id),
  CONSTRAINT chk_course_credits CHECK (credits BETWEEN 1 AND 6),
  CONSTRAINT chk_course_type CHECK (
    course_type IN ('MAJOR_REQUIRED', 'MAJOR_ELECTIVE', 'LIBERAL_REQUIRED', 'LIBERAL_ELECTIVE', 'GENERAL')
  ),
  CONSTRAINT chk_course_english CHECK (is_english IN (0, 1))
);

COMMENT ON TABLE course IS '강의 카탈로그';
COMMENT ON COLUMN course.course_code IS '학수번호 (예: CSE3033)';
COMMENT ON COLUMN course.target_year IS '권장 학년';
COMMENT ON COLUMN course.is_english IS '영어 강의 여부';

CREATE INDEX idx_course_dept_type ON course (dept_id, course_type);

CREATE TABLE prerequisite (
  prereq_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id NUMBER(19) NOT NULL,
  required_course_id NUMBER(19) NOT NULL,
  CONSTRAINT pk_prerequisite PRIMARY KEY (prereq_id),
  CONSTRAINT fk_prerequisite_course FOREIGN KEY (course_id) REFERENCES course (course_id) ON DELETE CASCADE,
  CONSTRAINT fk_prerequisite_required_course FOREIGN KEY (required_course_id) REFERENCES course (course_id),
  CONSTRAINT uk_prerequisite UNIQUE (course_id, required_course_id)
);

COMMENT ON TABLE prerequisite IS '선수과목';

CREATE TABLE semester (
  semester_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  year NUMBER(10) NOT NULL,
  term VARCHAR2(10) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_current NUMBER(1) DEFAULT 0,
  CONSTRAINT pk_semester PRIMARY KEY (semester_id),
  CONSTRAINT uk_semester_year_term UNIQUE (year, term),
  CONSTRAINT chk_semester_term CHECK (term IN ('SPRING', 'SUMMER', 'FALL', 'WINTER')),
  CONSTRAINT chk_semester_current CHECK (is_current IN (0, 1))
);

COMMENT ON TABLE semester IS '학기 정보';

CREATE TABLE classroom (
  classroom_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  building VARCHAR2(50) NOT NULL,
  room_no VARCHAR2(20) NOT NULL,
  capacity NUMBER(10) NOT NULL,
  has_projector NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_classroom PRIMARY KEY (classroom_id),
  CONSTRAINT uk_classroom_room UNIQUE (building, room_no),
  CONSTRAINT chk_classroom_projector CHECK (has_projector IN (0, 1))
);

COMMENT ON TABLE classroom IS '강의실';

CREATE TABLE course_section (
  section_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id NUMBER(19) NOT NULL,
  semester_id NUMBER(19) NOT NULL,
  professor_id NUMBER(19) NOT NULL,
  section_no VARCHAR2(10) NOT NULL,
  capacity NUMBER(10) NOT NULL,
  enrolled_count NUMBER(10) DEFAULT 0,
  waitlist_count NUMBER(10) DEFAULT 0,
  status VARCHAR2(10) DEFAULT 'OPEN',
  syllabus_url VARCHAR2(500),
  CONSTRAINT pk_course_section PRIMARY KEY (section_id),
  CONSTRAINT fk_course_section_course FOREIGN KEY (course_id) REFERENCES course (course_id),
  CONSTRAINT fk_course_section_semester FOREIGN KEY (semester_id) REFERENCES semester (semester_id),
  CONSTRAINT fk_course_section_professor FOREIGN KEY (professor_id) REFERENCES professor (professor_id),
  CONSTRAINT uk_course_section UNIQUE (course_id, semester_id, section_no),
  CONSTRAINT chk_course_section_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

COMMENT ON TABLE course_section IS '강의 분반';
COMMENT ON COLUMN course_section.section_no IS '분반 번호 (01, 02...)';
COMMENT ON COLUMN course_section.enrolled_count IS '현재 수강 인원 (트리거로 자동 관리)';

CREATE INDEX idx_course_section_semester_status ON course_section (semester_id, status);

CREATE TABLE section_schedule (
  schedule_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  section_id NUMBER(19) NOT NULL,
  classroom_id NUMBER(19) NOT NULL,
  day_of_week VARCHAR2(3) NOT NULL,
  start_time VARCHAR2(5) NOT NULL,
  end_time VARCHAR2(5) NOT NULL,
  CONSTRAINT pk_section_schedule PRIMARY KEY (schedule_id),
  CONSTRAINT fk_section_schedule_section FOREIGN KEY (section_id) REFERENCES course_section (section_id) ON DELETE CASCADE,
  CONSTRAINT fk_section_schedule_classroom FOREIGN KEY (classroom_id) REFERENCES classroom (classroom_id),
  CONSTRAINT chk_section_schedule_day CHECK (day_of_week IN ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT')),
  CONSTRAINT chk_section_schedule_start_time CHECK (REGEXP_LIKE(start_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT chk_section_schedule_end_time CHECK (REGEXP_LIKE(end_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$'))
);

COMMENT ON TABLE section_schedule IS '강의 시간표';
COMMENT ON COLUMN section_schedule.start_time IS 'HH24:MI 형식';
COMMENT ON COLUMN section_schedule.end_time IS 'HH24:MI 형식';

CREATE INDEX idx_section_schedule_day_time ON section_schedule (day_of_week, start_time);

CREATE TABLE registration_period (
  period_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  semester_id NUMBER(19) NOT NULL,
  period_type VARCHAR2(10) NOT NULL,
  target_year NUMBER(3),
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  CONSTRAINT pk_registration_period PRIMARY KEY (period_id),
  CONSTRAINT fk_registration_period_semester FOREIGN KEY (semester_id) REFERENCES semester (semester_id),
  CONSTRAINT chk_registration_period_type CHECK (period_type IN ('CART', 'MAIN', 'ADD_DROP', 'CANCEL'))
);

COMMENT ON TABLE registration_period IS '수강신청 기간 설정';
COMMENT ON COLUMN registration_period.target_year IS 'NULL이면 전체 학년 대상';

CREATE INDEX idx_registration_period_active ON registration_period (semester_id, start_at, end_at);

CREATE TABLE cart_item (
  cart_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id NUMBER(19) NOT NULL,
  section_id NUMBER(19) NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cart_item PRIMARY KEY (cart_id),
  CONSTRAINT fk_cart_item_student FOREIGN KEY (student_id) REFERENCES student (student_id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_section FOREIGN KEY (section_id) REFERENCES course_section (section_id) ON DELETE CASCADE,
  CONSTRAINT uk_cart_item UNIQUE (student_id, section_id)
);

COMMENT ON TABLE cart_item IS '수강신청 장바구니';

CREATE TABLE waitlist (
  waitlist_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id NUMBER(19) NOT NULL,
  section_id NUMBER(19) NOT NULL,
  position NUMBER(10) NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_waitlist PRIMARY KEY (waitlist_id),
  CONSTRAINT fk_waitlist_student FOREIGN KEY (student_id) REFERENCES student (student_id) ON DELETE CASCADE,
  CONSTRAINT fk_waitlist_section FOREIGN KEY (section_id) REFERENCES course_section (section_id) ON DELETE CASCADE,
  CONSTRAINT uk_waitlist UNIQUE (student_id, section_id)
);

COMMENT ON TABLE waitlist IS '수강 대기열';
COMMENT ON COLUMN waitlist.position IS '대기 순번';

CREATE INDEX idx_waitlist_section_position ON waitlist (section_id, position);

CREATE TABLE enrollment (
  enrollment_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id NUMBER(19) NOT NULL,
  section_id NUMBER(19) NOT NULL,
  status VARCHAR2(10) DEFAULT 'ENROLLED',
  enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dropped_at TIMESTAMP,
  CONSTRAINT pk_enrollment PRIMARY KEY (enrollment_id),
  CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES student (student_id),
  CONSTRAINT fk_enrollment_section FOREIGN KEY (section_id) REFERENCES course_section (section_id),
  CONSTRAINT uk_enrollment UNIQUE (student_id, section_id),
  CONSTRAINT chk_enrollment_status CHECK (status IN ('ENROLLED', 'DROPPED', 'COMPLETED'))
);

COMMENT ON TABLE enrollment IS '수강 신청 내역';

CREATE INDEX idx_enrollment_student_status ON enrollment (student_id, status);

CREATE TABLE grade (
  grade_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  enrollment_id NUMBER(19) NOT NULL,
  attendance_score NUMBER(5,2) DEFAULT 0,
  midterm_score NUMBER(5,2),
  final_score NUMBER(5,2),
  assignment_score NUMBER(5,2),
  total_score NUMBER(5,2),
  letter_grade VARCHAR2(2),
  grade_points NUMBER(3,2),
  is_finalized NUMBER(1) DEFAULT 0,
  finalized_at TIMESTAMP,
  CONSTRAINT pk_grade PRIMARY KEY (grade_id),
  CONSTRAINT uk_grade_enrollment_id UNIQUE (enrollment_id),
  CONSTRAINT fk_grade_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollment (enrollment_id) ON DELETE CASCADE,
  CONSTRAINT chk_grade_finalized CHECK (is_finalized IN (0, 1))
);

COMMENT ON TABLE grade IS '성적';
COMMENT ON COLUMN grade.letter_grade IS 'A+, A0, B+, B0, C+, C0, D+, D0, F';
COMMENT ON COLUMN grade.grade_points IS '4.5 만점 환산';

CREATE TABLE review (
  review_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  enrollment_id NUMBER(19) NOT NULL,
  rating_overall NUMBER(3) NOT NULL,
  rating_content NUMBER(3),
  rating_workload NUMBER(3),
  rating_professor NUMBER(3),
  difficulty VARCHAR2(10),
  pros CLOB,
  cons CLOB,
  advice CLOB,
  is_anonymous NUMBER(1) DEFAULT 1,
  helpful_count NUMBER(10) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_review PRIMARY KEY (review_id),
  CONSTRAINT uk_review_enrollment_id UNIQUE (enrollment_id),
  CONSTRAINT fk_review_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollment (enrollment_id) ON DELETE CASCADE,
  CONSTRAINT chk_review_rating_overall CHECK (rating_overall BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_content CHECK (rating_content BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_workload CHECK (rating_workload BETWEEN 1 AND 5),
  CONSTRAINT chk_review_rating_professor CHECK (rating_professor BETWEEN 1 AND 5),
  CONSTRAINT chk_review_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
  CONSTRAINT chk_review_anonymous CHECK (is_anonymous IN (0, 1))
);

COMMENT ON TABLE review IS '강의 평가';

CREATE TABLE notification (
  notification_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id NUMBER(19) NOT NULL,
  title VARCHAR2(200) NOT NULL,
  body CLOB,
  type VARCHAR2(20) NOT NULL,
  is_read NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notification PRIMARY KEY (notification_id),
  CONSTRAINT fk_notification_student FOREIGN KEY (student_id) REFERENCES student (student_id) ON DELETE CASCADE,
  CONSTRAINT chk_notification_type CHECK (type IN ('ENROLLMENT', 'WAITLIST', 'GRADE', 'ANNOUNCEMENT', 'SYSTEM')),
  CONSTRAINT chk_notification_read CHECK (is_read IN (0, 1))
);

COMMENT ON TABLE notification IS '학생 알림';

CREATE INDEX idx_notification_student_unread ON notification (student_id, is_read, created_at DESC);

CREATE TABLE announcement (
  announcement_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  author_user_id NUMBER(19) NOT NULL,
  title VARCHAR2(200) NOT NULL,
  body CLOB,
  scope VARCHAR2(20) NOT NULL,
  target_dept_id NUMBER(19),
  target_section_id NUMBER(19),
  is_pinned NUMBER(1) DEFAULT 0,
  posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_announcement PRIMARY KEY (announcement_id),
  CONSTRAINT fk_announcement_author FOREIGN KEY (author_user_id) REFERENCES user_account (user_id),
  CONSTRAINT fk_announcement_department FOREIGN KEY (target_dept_id) REFERENCES department (dept_id) ON DELETE SET NULL,
  CONSTRAINT fk_announcement_section FOREIGN KEY (target_section_id) REFERENCES course_section (section_id) ON DELETE SET NULL,
  CONSTRAINT chk_announcement_scope CHECK (scope IN ('GLOBAL', 'DEPARTMENT', 'SECTION')),
  CONSTRAINT chk_announcement_pinned CHECK (is_pinned IN (0, 1))
);

COMMENT ON TABLE announcement IS '공지사항';

CREATE INDEX idx_announcement_scope_posted ON announcement (scope, posted_at DESC);
